default_profile: prod

shared:
  google:
    service_account_json: "secrets/google_sa.json"
    sheet_url: "https://docs.google.com/spreadsheets/d/1i2eREe8Tb4x7FUavSOA6IMeZBwWUv29T3RzrN9S5NqU/edit?" ## aca va la url de la hoja de google sheets


### Este es el mail que debe ser editor en la hoja de Google = gsheet-runner@export-snow-to-drive.iam.gserviceaccount.com

  snowflake:
    service_account_json: "secrets/snowflake_sa.json"

  queries:
    - file: "sql/Consulta1.sql"   ## aca el nombre del archivo sql y la carpeta donde esta
      worksheet: "Competencia"    ## aca el nombre de la hoja en google sheets
      range: "A2"             ## aca el desde que celda queres que pegue el resultado del query (se puede retir cuanto se quiera dentro del mismo archivo)

    - file: "sql/Consulta2.sql"  
      worksheet: "Actualizado"    
      range: "A2" 

    - file: "sql/Consulta3.sql"  
      worksheet: "CLIENTESXLOCAL"    
      range: "A2" 

  
profiles:
  test:
    env: test

  prod:
    env: prod
